### PR TITLE
Docs/add mail api key guide

### PR DESCRIPTION
**Pull request by chavdarohit**
Description:-
#8 issue
This PR adds a detailed guide on how to create a mail API key using the Google Developer Console. It provides step-by-step instructions, including:

Creating a new Google Cloud project
Enabling the Gmail API
Generating API credentials (API key)
Setting optional restrictions for enhanced security
Additionally, the Expected Outcome section has been structured into three clear points for improved clarity and understanding.

Changes Included:-
New documentation on creating a personalized mail API key
Updated instructions for seamless integration into npm packages for sending OTPs via email
Reason for Update:
To assist users in efficiently generating API keys and integrating them with the npm package for sending OTPs via email.

### CODE REVIEW

**Review by aditya-garg-09-01-2002 — CHANGES_REQUESTED** [review]
### 5. 📜 Generate a Refresh Token

Tip :- You can use the internal application, which allows a longer period for API tokens before expiry.

1. Go to [OAuth 2.0 Playground](https://developers.google.com/oauthplayground/).
2. In the top-right corner, click the **Settings** icon.
3. Check the box for **Use your own OAuth credentials** and fill in your **Client ID** and **Client Secret**.
4. For **API URL**, enter: `https://mail.google.com`.
5. Click **Authorize APIs** and complete the authorization process to get an authorization code.
6. Use this authorization code to generate a refresh token.



### 6. 💾 Save and Use the API Key

- Following credentials will be required (present in .env file already) :-
  - MAIL_CLIENT_ID=""
  - MAIL_CLIENT_SECRET=""
  - MAIL_REDIRECT_URI='https://developers.google.com/oauthplayground'
  - MAIL_REFRESH_TOKEN=""
  - MAIL_SERVICE="gmail"
  - SENDER_MAIL="your-mail-id"
- Store the API key and refresh token in a secure place, such as an environment configuration file (e.g., `.env` for Node.js).
- Use this API key within your npm package to send OTPs via email.

**Comment by chavdarohit** [comment]
the PR is updated as per your requirement sir

**Review by aditya-garg-09-01-2002 — APPROVED** [review]
Yup, its great, thanks for the contribution.

**Comment by chavdarohit** [comment]
Thanks for merging also i am opening the discussion for the same and about the labels can you update it for the hacktoberfest-accepted or other necessary labels

**Comment by aditya-garg-09-01-2002** [comment]
Required Labels are already there, there's no need for hacktoberfest-accepted label, already accepted a hacktoberfest participating repo's task.
This PR will reflect on the official website as well.

**Pull request merged**
