### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Akshay-66**
Hacktoberfest Contribution

Updated Readme.md file for commencer (q-auth)
- made up easy to access - developer friendly deployment description
- 4 different sections about the API Endpoints

### CODE REVIEW

**Review by aditya-garg-09-01-2002 — CHANGES_REQUESTED** [review]
Great work!!!
For now it's good but somethings we can do, then we can move ahead with merging 
- [ ] You have specified all routes are listed below, which does not seem to be the case for now, so we can do some routes are listed below (ref Point 4. API end-points description)
- [ ] /auth/register-user is the route instead of /auth/register. 
- [ ] inputs are userId, idType (represents whether a mobile device if idType = "mobile" or email is used idType ="email), and name (represents user name)
- [ ] /auth/verify-otp does not exists, kindly remove it
- [ ] /auth/reset-password exists but controller does a different job, its meant to reset a password for users' who have valid otp and already have set a password. method "PUT", inputs - otp, userId, password
- [ ] similarly /auth/set-password exists instead of /auth/new-password,controller's job its meant to set a password for users' who have valid otp but never have set the password earlier. method "PUT", inputs - otp, userId, password
- [ ] Get /auth/me does not exists for now, kindly remove it as well.

**Comment by aditya-garg-09-01-2002** [comment]
You can change the description of your commit from the browser itself, kindly make it a bit more descriptive like what you did and how was that accomplished.

**Review by aditya-garg-09-01-2002 — CHANGES_REQUESTED** [review]
- Nice progress, just one thing still not sorted.
- addition of put method in reset-password and set-password is done but if you see , in heading method is written as POST, kindly correct that part.
- POST method written can be seen in the screen shot below, next to S. No.
- 
image

**Review by Akshay-66 — COMMENTED** [review]
Changed POST to PUT in reset-password and set-password.

**Review by aditya-garg-09-01-2002 — APPROVED** [review]
The APIs concerned are documented well.
Thanks for contributing.

**Comment by Akshay-66** [comment]
Thank you so much @aditya-garg-09-01-2002 
- Guided me in very friendly manner

Marking my first "hacktoberfest-accepted" here 😄

**Pull request merged**
