### PR TITLE
fix : issue 45 - name argument included in sendOtp

### LINKED ISSUE #45: [Bug]: Fixing sendOtp function in forgotPassword controller
**Describe the bug**

- Following up on the discussion in issue #33 and the successful PR #36.
- forgotPassword controller is still calling the function definition for sendOtp function.

**To Reproduce**

N/A

**Expected behavior**

- forgotPassword controller now also sendOtp function call.
- function call must be updated
- it shall also include the name argument.

**Screenshots**

None

**Your PC/browser/dev tool specifications (please complete the following information):**

N/A

**Additional context**

Ref file - src/controllers/user/forgotPassword.ts

### PR DESCRIPTION
**Pull request by hasin-zaman**
closes #45

### CODE REVIEW

**Comment by hasin-zaman** [comment]
I have fetched profile using req.userID and have passed profile.name as 4th argument to sendOTP resolving the errors

**Review by aditya-garg-09-01-2002 — CHANGES_REQUESTED** [review]
- don't extract data again from database in forgotPassword controller.
- update the getUserDetails middleware to extract profile as well, we are for now using prisma, if you need help with syntax, do let me know. (```{where:{userId:req.userID}}``` -> ```{where:{userId:req.userID},include:{profile:true}}``` will get things done btw) in the ```function getUserDetails()```
- profile is supposed to be extracted in the middleware - getUserDetails.
- you can put in user.profile.name instead of user.profile!.name

**Comment by hasin-zaman** [comment]
But user.profile is nullable shouldn't user.profile.name instead of user.profile!.name give error?

**Comment by aditya-garg-09-01-2002** [comment]
- The setup of user registration is such that forgot password won't ever work without setting up the profile, thus name and profile won't be null.
- Even if due to some bug, this situation arises, the thing is user.profile! name only asserts profile is not null, but if user.profile is still, the error would occur irrespective of user.profile.name or user.profile!.name ( this will only shift compile time error to a run time error instead.

**Review by aditya-garg-09-01-2002 — APPROVED** [review]
- Yup, great
- Thanks for contributing
- Hope to see you on more issues :)

**Pull request merged**
