### PR TITLE
feat: integrate hbsToHtml for OTP email templates and update sendOtp logic

### PR DESCRIPTION
**Pull request by chavdarohit**
Integrates `hbsToHtml` for generating OTP email templates and updates the `sendOtp` function to handle user name and OTP correctly. Refactors `mailOtp` to send dynamic HTML content using Handlebars templates.

### CODE REVIEW

**Comment by aditya-garg-09-01-2002** [comment]
- All uploaded files looks good
- Missing package-lock.json

**Comment by chavdarohit** [comment]
ohh okay i look for that

**Comment by chavdarohit** [comment]
@aditya-garg-09-01-2002 updated the PR with the package lock json

**Review by aditya-garg-09-01-2002 — APPROVED** [review]
Yup looks great, I will get to its testing in a while.
Thanks

**Pull request merged**
